name: Auto commit

on:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 */6 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Update timestamp
        run: date '+%Y-%m-%dT%H:%M:%SZ' > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "chore(bot): 🟩 auto commit" || exit 0

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}